### ISSUE TITLE
A little bit confused.

### ISSUE THREAD

**Issue by Jimmy-Z** [wangyu-/tinyPortMapper#22]
What's the use case here? wouldn't netfilter DNAT be more performant?

**Comment by wangyu-** [comment]
1st, netfilter is only avaliable on linux. This programs is cross-platform.

2nd, netfiler forwarding is more easily to make mistakes. 

For example, for this forwarding rule:
```
iptables -t nat -A PREROUTING -p tcp --dport 440 -j DNAT --to-destination 45.78.17.159:443
iptables -t nat -A POSTROUTING -p tcp -d 45.78.17.159 --dport 443 -j SNAT --to-source 45.76.100.53
```
Or this one:
```
iptables -t mangle -A PREROUTING -p tcp -d45.76.100.53 --dport 440 -j MARK --set-mark 0x1000
iptables -t nat -A PREROUTING -p tcp -m mark --mark 0x1000 -j DNAT --to-destination 45.78.17.159:443
iptables -t nat -A POSTROUTING -p tcp -m mark --mark 0x1000 -j SNAT --to-source 45.76.100.53
```
They works as expected usually.  
If I remembered correctly, if the DNAT or SNAT target is local machine, then it just fails. Since netfilter treats local differently.  You got bite easily by boundary cases.

But if you are on linux and very familiar with netfilter, you should just use netfiler for best performance.

**Comment by Jimmy-Z** [comment]
Thanks for the explanation.

Just FYI, Windows also has a netsh command called portproxy, which does basically the samething.
https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-interface-portproxy
the link is for Windows Server but it's also available on consumer SKUs.
